services:
  - type: web
    name: dexmateai
    env: python
    pythonVersion: "3.10"  # Explicitly set stable Python version
    buildCommand: |
      python -m pip install --upgrade pip &&
      pip install wheel setuptools &&
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7866890680:AAFfFtyIv4W_8_9FohReYvRP7wt9IbIJDMA
      - key: OPENROUTER_API_KEY
        value: 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
      - key: ENVIRONMENT
        value: production
      - key: WEBHOOK_URL
        value: https://dexmateai.onrender.com