services:
  - type: web
    name: dexmateai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Main.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token
      - key: OPENAI_API_KEY
        value: your_openai_key
      - key: WEBHOOK_URL
        value: https://dexmateai.onrender.com